FROM node:12.10.0

COPY package*.json ./data/

WORKDIR /data

RUN npm install --only=prod

ENV PATH /data/node_modules/.bin:$PATH

COPY . /data/app
WORKDIR /data/app

EXPOSE 3000

CMD ["npm", "run", "build"]