version: '3'

services:
  pwa:
    build:
      context: ./pwa
    volumes:
      - ./pwa/:/app
    ports:
      - "3000:3000"
    container_name: haiti_pwa
    
  database:
    image: "postgres" # use latest official postgres version
    env_file:
      - ./db/database.env # configure postgres
    volumes:
      - database-data:/var/lib/postgresql/data/ # persist data even if container shuts down
    ports:
      - "5432:5432"        
volumes:
  database-data: # named volumes can be managed easier using docker-compose
