name: Lighthouse
on: push
jobs:
  static-dist-dir:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Install requirements
        run: pushd pwa && npm install && popd
      - name: Build
        run: pushd pwa && npm run build && popd
      - name: Run Lighthouse against a static dist dir
        uses: treosh/lighthouse-ci-action@v2
        with:
          configPath: "./github/lighthouse/main.json"
