name: Build project and Run Lighthouse CI
on: [push]
jobs:
  lhci:
    name: Lighthouse CI
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js 10.x
        uses: actions/setup-node@v1
        with:
          node-version: 10.x
      - name: npm install, build
        run: |
          pushd pwa && npm install
          npm run build && popd
      - name: run Lighthouse CI
        run: |
          npm install -g @lhci/cli@0.3.x
          lhci autorun || echo "LHCI failed!"
      - name: Upload lighthouse report
        uses: actions/upload-artifact@v1
        with:
          name: lighthouse
          path: ./.lighthouseci