name: PWA Testing

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node Version ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - run: pushd pwa && npm install && popd
      - run: pushd pwa && npm run build && popd
      - run: pushd pwa && npm test:cov && popd
      - run: pushd pwa && npm cy:run && popd
        env:
          CI: true
